version: "3.7"
services:
  db:
    image: postgres
    # In production systems, We should never put the below details
    # directly. They should be appended based on the environments using CI
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cyclone-intel
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build: ./
    depends_on:
      - db
    ports:
      - "8080:8080"