version: "3.7"
services:
  base_image :
    build : ./
  db:
    image: postgres
    # In production systems, We should never put the below details
    # directly. They should be appended based on the environments using CI
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cyclone-intel
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build: ./server
    depends_on:
      - base_image
      - db
    ports:
      - "8080:8080"
  scheduler:
    build: ./ninja-scraper
    depends_on :
      - base_image
      - db
    ports:
      - "8081:8080"